config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'users/carousel', to: 'users#carousel'
  get 'users/ranking' , to: 'users#ranking'

  root 'board#show'

  get 'board/show'
  post 'board/show'

  get 'board/new'

  get 'board/index', to: 'board#index'

  get 'board/create', to: 'board#create'

  get 'board/share', to: 'board#share'
  get 'board/confirmation', to: 'board#confirmation'
  post '/users/show'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }



  get 'match/index', to: 'match#index'
  get 'match/show', to: 'match#show'

  get 'users/show', to: 'users#show'

  post 'board/confirmation'

  get 'board/next', to: 'board#next', as: 'next'
  get 'board/match', to: 'board#match', as: 'match'
  get 'randomizers/reset', to: 'randomizers#reset'
end

#devise_for :users, controllers: {
#        sessions: 'users/sessions'
#      }

app/models/board.rb
class Board < ApplicationRecord
  has_and_belongs_to_many :users

  #belongs_to :creator, class_name: "User"
  #has_many :candidates, class_name: "User"
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
before_action :my_authentication

  def my_authentication
     unless user_signed_in? 
        redirect_to users_carousel_path
     end
  end

  def random
    puts '================'
    puts '================'
    puts '==RANDOM START=='
    puts '================'
    puts '================'

    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last

    ids = User.pluck(:id)
    ids.delete_if {|id| id == current_user.id }
    fate = ids.shuffle[0..1]
    board.user_ids = [fate[0], fate[1]]
    board.users = [User.find(fate[0]), User.find(fate[1])]
    board.save
    
    current_user.randomize = false
    current_user.save
  end
 
  def show
    #tempboard = Board.where(user_id: current_user.id)
    if current_user.randomize == true
      self.random
    end
    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last
    @candidate_1 = board.users.first
    @candidate_2 = board.users.last
  end
 
  def next
    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last
    candidate_1 = board.users.first
    candidate_2 = board.users.last
    
    ab = ArchivedBoard.new(user_id: current_user.id)
    ab.user_ids=[candidate_1.id, candidate_2.id]
    ab.is_match = false
    ab.save
    
    current_user.randomize = true
    current_user.save
    
    redirect_to root_path
  end
 
  def confirmation
    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last
    @candidate_1 = board.users.first
    @candidate_2 = board.users.last
  end
 
  def match
    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last
    candidate_1 = board.users.first
    candidate_2 = board.users.last
    
    ab = ArchivedBoard.new(user_id: current_user.id)
    ab.user_ids=[candidate_1.id, candidate_2.id]
    ab.is_match = true
    ab.save
    
    m = Match.new(user_id: current_user.id)
    m.user_ids=[candidate_1.id, candidate_2.id]
    candidate_1.karma += 1
    candidate_2.karma += 1
    candidate_1.save!
    candidate_2.save!
    m.save
    
    current_user.randomize = true
    current_user.karma += 2
    current_user.save
    redirect_to board_share_path
  end
 
##################################################################
 
  def share
  end
 
  def index
  end
 
  def get_ids
  end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/board/confirmation.html.erb
<div class="container container-confirmation">
    <div class="title-confirmation">
      It's a match !
    </div>

    <div class="pictures-confirmation">
      <div class="pix-layer">
        <div id="first" class="yellow-circle"></div>
        <div id="second" class="yellow-circle"></div>
        <div id="third" class="blue-circle" ></div>
        <div id="fourth" class="blue-circle" ></div>
        <div id="fith" class="green-circle" ></div>
        <div id="sixth" class="green-circle" ></div>
        <%= image_tag @candidate_1.avatar.url(:thumb), class: "circle-image" %>
        <%= image_tag @candidate_2.avatar.url(:thumb), class: "circle-image" %>

      </div>
    
    </div>
      <a target="_blank" class="CTA_button"
        <%= mail_to "#{@candidate_1.email}", "ENVOI D'E-MAIL!", cc: "#{@candidate_2.email}", subject: "#{@candidate_1.firstname} & #{@candidate_2.firstname}, je pense que vous pourriez bien vous entendre ! ", body:"Hello #{@candidate_1.firstname} & #{@candidate_2.firstname}, 
          \n Je vous ai fait matcher sur Obviews ! Je pense que vous aimeriez vous rencontrer, pour les raisons suivantes :
          \n \n \n
          \n A très vite,
          \n #{@current_user.firstname}
          \n \n Retrouvez-vous sur www.obviews.com"
        %>
      </a>

      <%= link_to "Valide le match", match_path, class: "action-button"%>

    <div class="action_link" style="margin-top: 30px">
      <%= link_to "Annuler", root_path %>
    </div>
</div>



<!--     <div class="CTA_button">
          <a href='#'>ENVOIE !</a>
    </div> -->

app/views/board/get_ids.html.erb
<h1>Board#get_ids</h1>
<p>Find me in app/views/board/get_ids.html.erb</p>

app/views/board/new.html.erb
<h1>Board#new</h1>
<p>Find me in app/views/board/new.html.erb</p>

app/views/board/share.html.erb
<div class="container container-share">
    <div class="text-share">
        <p>Obviews, c’est évidemment <strong>mieux avec ses amis !</strong></p>
        <p class="yellow_p">Invite-les pour qu’ils puissent eux-aussi <strong>faire grandir leur communauté</strong>
          et <strong>te faire rencontrer leurs amis !</strong></p>
    </div>

    <div class="fb-share">
        <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fobviews-dev.herokuapp.com&layout=button&size=large&mobile_iframe=true&width=89&height=28&appId" width="89" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
    </div>

    <div class="action_link action_link_fb">
      <%= link_to "Retour", board_show_path %>
    </div>

</div>

app/views/board/show.html.erb
<!-- TOP CONTAINER -->
<div class= "candidate_1">
  <div class="bio behind">
    <p class="bio-description" id="click-frame-bio">
      <%= @candidate_1.bio %>
    </p>
    <div class="action-bar">
      <span class="user-name-display"><%= @candidate_1.firstname %> <%= @candidate_1.lastname %></span>
    </div>
  </div>
  <div class="picture ahead">
  
    <%= image_tag @candidate_1.avatar.url(:original), class: "img-fluid", :id=>"click-frame-pix"%>

    <div class="action-bar">
      <span class="user-name-display"><%= @candidate_1.firstname %> <%= @candidate_1.lastname %></span>
    </div>
  </div>
</div>
<!-- MIDDLE -->
<div class= "middle-container post_lock_state">
    <%= link_to users_show_path(current_user), class: "child" do %>
      <%= image_tag current_user.avatar.url(:thumb), class: "circle-image"  %>
    <% end %>
      <div class=" action-button">
        <%= link_to "MATCH!", board_confirmation_path %>
      </div>
    <%= link_to 'Next', next_path, class: "action_link child", method: :get %>
</div>
<!-- BOTTOM CONTAINER -->
<div class= "candidate_2">
  <div class="bio behind">
    <p class="bio-description" id="click-frame-bio">
      <%= @candidate_2.bio %>
    </p>
    <div class="action-bar">
      <span class="user-name-display"><%= @candidate_2.firstname %> <%= @candidate_2.lastname %></span>
    </div>
  </div>
  <div class="picture ahead">
    <%= image_tag @candidate_2.avatar.url(:original), class: "img-fluid", :id=>"click-frame-pix"%>
    <div class="action-bar">
      <span class="user-name-display"><%= @candidate_2.firstname %> <%= @candidate_2.lastname %></span>
    </div>
  </div>
</div>

app/views/board/show.js.erb
console.log('test');
    