config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'users/carousel', to: 'users#carousel'
  get 'users/ranking' , to: 'users#ranking'

  root 'board#show'

  get 'board/show'
  post 'board/show'

  get 'board/new'

  get 'board/index', to: 'board#index'

  get 'board/create', to: 'board#create'

  get 'board/share', to: 'board#share'
  get 'board/confirmation', to: 'board#confirmation'
  post '/users/show'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }



  get 'match/index', to: 'match#index'
  get 'match/show', to: 'match#show'

  get 'users/show', to: 'users#show'

  post 'board/confirmation'

  get 'board/next', to: 'board#next', as: 'next'
  get 'board/match', to: 'board#match', as: 'match'
  get 'randomizers/reset', to: 'randomizers#reset'
end

#devise_for :users, controllers: {
#        sessions: 'users/sessions'
#      }

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :boards
  has_and_belongs_to_many :archived_boards
  has_and_belongs_to_many :matches
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  validates :firstname, presence: true, length: { in: 2..50 }
  validates :lastname, presence: true, length: { in: 2..50 }

  #FRENCH_PHONE_REGEX = ^(0|\+33)[1-9]([-. ]?[0-9]{2}){4}$
  #validates :lastname, presence: true, length: { in: 2..50 }
  #validates :bio, presence: true
  #validates :phone, presence: true, format: { with: FRENCH_PHONE_REGEX }

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }, :default_url => ":style/missing_avatar.png"  # Can't seed db if these lines aren't commented
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/    # Can't seed db if these lines aren't commented
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up


  # def new
  #   super
  # end
  # POST /resource
  #def create
  #  build_resource(sign_up_params)

   # resource.save
   # yield resource if block_given?
   # if resource.persisted?
    #  if resource.active_for_authentication?
     #   set_flash_message! :notice, :signed_up
      #  sign_up(resource_name, resource)
       # respond_with resource, location: after_sign_up_path_for(resource)
       # puts "envoie de l'email"
       # UserMailer.welcome_email(current_user.email).deliver_now!
      #else
      #  set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
      #  expire_data_after_sign_in!
      #  respond_with resource, location: after_inactive_sign_up_path_for(resource)
      #end
    #else
    #  clean_up_passwords resource
    #  set_minimum_password_length
    #  respond_with resource
   # end
 # end
  def create
    super
    puts '================================================'
    puts '================================================'
    puts '================================================'
    puts '=================SIGN UP========================'
    puts '================================================'
    puts '================================================'
    puts '================================================'
    Board.create(user_id: resource.id) if resource.boards == []
  end

  #POST /resource
  # def create
  #   super 
  # end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
    puts '================================================'
    puts '================================================'
    puts '================================================'
    puts '===============SIGN IN=========================='
    puts '================================================'
    puts '================================================'
    puts '================================================'
    Board.create(user_id: current_user.id) if current_user.boards == []

    tempboard = Board.where(user_id: current_user.id)
    board = Board.find(tempboard.ids).last

    ids = User.pluck(:id)
    ids.delete_if {|id| id == current_user.id }
    fate = ids.shuffle[0..1]
    board.user_ids = [fate[0], fate[1]]
    board.users = [User.find(fate[0]), User.find(fate[1])]
    board.save
    
    current_user.randomize = false
    current_user.save
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def carousel
  end

  def ranking
    @bestusers = User.all.order(:karma).reverse
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/carousel.html.erb
<div class="container container-big-carousel">
    <div class="container-carousel">
        <div class="container container-carousel-top">
            <div class="scroller">
                <div>
                  <h1>Bienvenue sur Obviews&nbsp!</h1>
                  <img src="https://i.imgur.com/lo6cyh3.png" alt="carousel1" width="70%">
                  <p>Fais de nouvelles rencontres <strong>par l'intermédiaire de tes amis !</strong></p>
                </div>

                <div>
                  <h1>Fais matcher tes amis…</h1>
                  <img src="https://i.imgur.com/AOkVcgu.png" alt="carousel2" width="70%">
                  <p>Quand tu le sens bien, <strong>déclare le match !</strong> Sinon, passe au suivant.</p>
                </div>

                <div>
                  <h1>… Et gagne du karma&nbsp!</h1>
                  <img src="https://i.imgur.com/NutGdTH.png" alt="carousel3" width="70%">
                  <p>À chaque match initié, <strong>tu gagnes des points de karma.</strong></p>
                </div>
            </div>
        </div>

        <div class="CTA_button">
          <%= link_to "JE M'INSCRIS", new_user_registration_path %>
        </div>
        <div class="action_link">
          <%= link_to "Je me connecte", new_user_session_path %>
        </div>
    </div>
</div>

app/views/users/ranking.html.erb
<div class="container-ranking">
    <div class="container-match-index">
    <%= link_to users_show_path do %><i class="material-icons">chevron_left</i><% end %>
      <h1> Captains Obviews </h1>
    </div>

    <% i=1 %>
    <% @bestusers.each do |u| %>

      <% if i==1 %>
        <% if u.id != current_user.id %>
          <div class="rank-div" style="border: 5px solid rgba(56,252,140, 1);">
        <% elsif u.id == current_user.id %>
          <div class="rank-div" style="border: 5px solid yellow;">
        <% end %>
            <div class="who">
              <span class="ranking"><%= i %></span>
              <%= image_tag u.avatar.url(:thumb), class: "circle-image"  %>
              <span class="player-name" style="font-size: 1.1em;">
                <strong><%= u.firstname %> <%= u.lastname %> </strong>
              </span>
            </div>
            <div class="ranking-score">
              <span class="score"><%= u.karma %></span>
              <span class="emoji">✨</span>
            </div>
          </div>
      <% elsif i==2 %>
          <% if u.id != current_user.id %>
          <div class="rank-div" style="border: 3px solid rgba(56,252,140, .6);">
        <% elsif u.id == current_user.id %>
          <div class="rank-div" style="border: 5px solid yellow;">
        <% end %>
            <div class="who">
              <span class="ranking"><%= i %></span>
              <%= image_tag u.avatar.url(:thumb), class: "circle-image"  %>
              <span class="player-name">
                <%= u.firstname %>
                <%= u.lastname %>
              </span>
            </div>
            <div class="ranking-score">
              <span class="score"><%= u.karma %></span>
              <span class="emoji">✨</span>
            </div>
          </div>
      <% elsif i==3 %>

          <% if u.id != current_user.id %>
          <div class="rank-div" style="border: 3px solid rgba(56,252,140, .4);">
        <% elsif u.id == current_user.id %>
          <div class="rank-div" style="border: 5px solid yellow;">
        <% end %>
            <div class="who">
              <span class="ranking"><%= i %></span>
              <%= image_tag u.avatar.url(:thumb), class: "circle-image"  %>
              <span class="player-name">
                <%= u.firstname %>
                <%= u.lastname %>
              </span>
            </div>
            <div class="ranking-score">
              <span class="score"><%= u.karma %></span>
              <span class="emoji">✨</span>
            </div>
          </div>
      <% else %>
          <% if u.id != current_user.id %>
          <div class="rank-div">
        <% elsif u.id == current_user.id %>
          <div class="rank-div" style="border: 5px solid yellow;">
        <% end %>
            <div class="who">
              <span class="ranking"><%= i %></span>
              <%= image_tag u.avatar.url(:thumb), class: "circle-image"  %>
              <span class="player-name">
                <%= u.firstname %>
                <%= u.lastname %>
              </span>
            </div>
            <div class="ranking-score">
              <span class="score"><%= u.karma %></span>
              <span class="emoji">✨</span>
            </div>
          </div>
      <% end %>

    <% i+=1 %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container container-my-profile">
    <div class= "my-profile">
      <div class="my-bio behind">
        <p class="bio-description-self">
          <%= current_user.bio %>
        </p>
        <div class="action-bar">
          <span class="user-name-display"><%= current_user.firstname %> <%= current_user.lastname %></span>
            <%= link_to edit_user_registration_path do %>
              <i class="material-icons material-icons-edit" style="font-size: 30px">mode_edit</i>
            <% end %>
        </div>
      </div>
      <div class="picture-self ahead">
        <%= image_tag current_user.avatar.url(:original), class: "img-fluid"  %>
        <div class="action-bar">
          <span class="user-name-display"><%= current_user.firstname %> <%= current_user.lastname %></span>
            <%= link_to edit_user_registration_path do %>
              <i class="material-icons material-icons-edit" style="font-size: 30px">mode_edit</i>
            <% end %>
        </div>
      </div>
    </div>

    <div class="karma-score">
      <div>
        <span class="emoji" style="font-size: 25px">✨</span><span> <%= current_user.karma %></span>
      </div>
      <div><iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fobviews-dev.herokuapp.com&layout=button&size=large&mobile_iframe=true&width=89&height=28&appId" width="89" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></div>
      <div>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="material-icons exit-icon" style="font-size: 25px">exit_to_app</i>
        <% end %>
      <% end %>
      </div>
    </div>

    <div class="views-button">
      <%= link_to "Mes views", match_index_path %>
    </div>

    <div class="ranking-button">
      <%= link_to "Classement", users_ranking_path %>
    </div>

    <div class="action_link action_link_user-show">
      <%= link_to "Retour", board_show_path %>
    </div>
</div>